### ISSUE TITLE
TODO: separate data from code (publications, Members, gallery...)

### ISSUE THREAD

**Issue by FeynmanDNA** [FeynmanDNA/website-yjgroup-nus#1]
**publicationList  should just contain data**
separate from the markup
the UI layer should add the markup

publication list js --> write a script to convert the list to contain just the data fields, like {pubTitle: ..., pubAuthor:...}

and in another file just the html template, only once

and add a comment "if you want to edit the HTMl ,refer to the other file

**Comment by FeynmanDNA** [comment]
you can use jquery datatables
they load all data on the client and paginate automatically
and you can still search

**Comment by ghost** [comment]
🐮

iPhoneから送信

2018/06/07 21:27、KYY <notifications@github.com> のメッセージ:

**Comment by FeynmanDNA** [comment]
with 99247d4c1c39f1b45532fdf561f25ea55ded89a2

**Comment by FeynmanDNA** [comment]
solved with 99247d4c1c39f1b45532fdf561f25ea55ded89a2
